module 9 Spring MVC & JSP
alextimonov/GoJavaEnterprise pull request #8
Opened 2016-09-09 09:54 UTC by alextimonov

2016-09-09 10:26 UTC, schaffe commented on src/main/java/ua/goit/timonov/enterprise/module_6_2/dao/jdbc/JdbcDishDAO.java
> +        List<Map<String, Object>> mapList = template.queryForList(sql, dish.getId());
Use streams here

2016-09-09 10:29 UTC, schaffe commented on src/main/java/ua/goit/timonov/enterprise/module_6_2/dao/jdbc/JdbcEmployeeDAO.java
> +        for (Map<String, Object> row : mapList) {
The same about streams

2016-09-15 18:17 UTC, alextimonov commented on src/main/java/ua/goit/timonov/enterprise/module_6_2/dao/jdbc/JdbcDishDAO.java
> +        List<Map<String, Object>> mapList = template.queryForList(sql, dish.getId());
fixed in all Jdbc..DAO classes

2016-09-15 18:17 UTC, alextimonov commented on src/main/java/ua/goit/timonov/enterprise/module_6_2/dao/jdbc/JdbcEmployeeDAO.java
> +        for (Map<String, Object> row : mapList) {
fixed in all Jdbc..DAO classes

2016-09-16 08:19 UTC, schaffe commented on src/main/java/ua/goit/timonov/enterprise/module_9/web/DishWebController.java
> +    private DishService dishService;
For me Constructor injection is preferrable.
Not sure if Spring supports it

2016-09-16 08:20 UTC, schaffe commented on src/main/java/ua/goit/timonov/enterprise/module_9/web/MainController.java
> +        return "contacts";
Use Constants here

2016-09-16 08:21 UTC, schaffe commented on src/main/webapp/WEB-INF/view/jsp/menus.jsp
> +            <th> ID </th>
remove whitespaces in xml/html/whatever

2016-09-16 08:22 UTC, schaffe requested changes

2016-09-19 06:37 UTC, alextimonov commented on src/main/java/ua/goit/timonov/enterprise/module_9/web/DishWebController.java
> +    private DishService dishService;
fixed, Spring supports it

2016-09-19 06:37 UTC, alextimonov commented on src/main/java/ua/goit/timonov/enterprise/module_9/web/MainController.java
> +        return "contacts";
fixed

2016-09-19 06:37 UTC, alextimonov commented on src/main/webapp/WEB-INF/view/jsp/menus.jsp
> +            <th> ID </th>
fixed

2016-09-21 09:14 UTC, schaffe commented on src/main/java/ua/goit/timonov/enterprise/module_9/web/DishWebController.java
> +    public DishWebController(DishService dishService) {
in future: if using constructor injection mark injected fields as `final`

2016-09-21 09:15 UTC, schaffe commented
to be merged

2016-09-21 09:29 UTC, merged